name: First workflow3

on: push

jobs:

  first-job3:

    runs-on: ubuntu-latest

    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
	with:
            node-version: "20"
      - name: install dependencies
        run: npm install

      - name: Run a one-line script
        run: echo " The ${{ github.repository }} repository has been cloned to the runner."