name: First workflow3
on: push
jobs:
  first-job3:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
	run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: ls ${{ github.workspace }}