name: First workflow2
on: push
jobs:
  first-job2:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
	with:
            node-version: "20"
      - name: install dependencies
        run: npm install
      - name: List files in the repository
        run: |
	  ls ${{ github.workspace }}
      - name: Run a one-line script
	run: echo " The ${{ github.repository }} repository has been cloned to the runner."
 
