name: First workflow2
on: push
jobs:
  first-job2:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls ${{ github.workspace }}
